version: 2
updates:
- package-ecosystem: github-actions
  directories:
  - /
  schedule:
    interval: monthly
  groups:
    actions:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /
  schedule:
    interval: monthly
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: "*"
    update-types: [version-update:semver-patch]
  target-branch: main
  allow:
  - dependency-type: direct
  groups:
    nestjs-dependencies:
      patterns:
      - "@nestjs*"
    otel-dependencies:
      patterns:
      - "@opentelemetry*"
    other-dependencies:
      patterns:
      - "*"
      exclude-patterns:
      - "@nestjs*"
      - "@opentelemetry*"
